kind: ZarfPackageConfig
metadata:
  name: blog-cluster
  description: "Cluster for serving my personal blog"
  version: 0.0.1
  architecture: arm64

# variables:
#   - name: VIP_INTERFACE
#     description: "Interface for the VIP"
#     prompt: true
#     sensitive: false


components:
  - name: cert-manager-chart
    charts:
      - name: cert-manager
        namespace: cert-manager
        url: https://charts.jetstack.io
        version: v1.12.1
        valuesFiles:
          - configs/cert-manager/values.yaml
    images:
      - quay.io/jetstack/cert-manager-controller:v1.12.1
      - quay.io/jetstack/cert-manager-webhook:v1.12.1
      - quay.io/jetstack/cert-manager-cainjector:v1.12.1
      - quay.io/jetstack/cert-manager-acmesolver:v1.12.1
      - quay.io/jetstack/cert-manager-ctl:v1.12.1
  
  - name: cert-manager-addons
    manifests:
    - name: cert-manager-addons
      namespace: cert-manager
      files:
      - configs/cert-manager/secret.yaml
      - configs/cert-manager/cluster-issuer.yaml

# https://github.com/brandtkeller/zarf-packages/tree/main/cloudflare-tunnel
  - name: import-cloudflare-tunnel
    import:
      name: cloudflare-tunnel
      url: oci://ghcr.io/brandtkeller/zarf/cloudflare-tunnel:0.0.2-skeleton

  - name: blog-certificate
    manifests:
    - name: blog-certificate
      namespace: blog
      files:
      - configs/nginx/certificate.yaml

## Insert nginx component here
## Add in a wait command for ready?
## TODO - containerports - configmap - antiaffinity - zarf ignore 
  - name: nginx-hugo
    manifests:
    - name: nginx
      namespace: blog
      files:
      - manifests/nginx/configmap.yaml
      - manifests/nginx/deployment.yaml
      - manifests/nginx/service.yaml
    # images:
    # - ghcr.io/brandtkeller/image/personal-blog:latest